-- Seed data (safe to re-run)
INSERT INTO public.equipement_class (code, label)
VALUES
    ('ALM', 'Alarme'),
    ('ASP', 'Aspirateur'),
    ('AM', 'Aspirateur de matiére'),
    ('BDP', 'Barre de pont'),
    ('BAL', 'Basculeur'),
    ('BET', 'Bétonniére '),
    ('BRO', 'Broyeur'),
    ('CER', 'Cercleuse'),
    ('CHL', 'Chalumeau'),
    ('CHA', 'Chariot'),
    ('CHF', 'Chauffage'),
    ('CN', 'CN'),
    ('COP', 'Compresseur'),
    ('COV', 'Convoyeur'),
    ('CDA', 'Cuve d''air'),
    ('DIA', 'Diable'),
    ('EER', 'Electro-Erosion'),
    ('ENR', 'Enrouleur'),
    ('ETU', 'Etuve'),
    ('EXT', 'Extrudeuse'),
    ('FIL', 'Filmeuse'),
    ('FSA', 'Filtre à sable'),
    ('FRS', 'Fraiseuse'),
    ('GRB', 'Gerbeur'),
    ('GRA', 'Granulateur '),
    ('GFR', 'Groupe froid'),
    ('GLT', 'Guillotine'),
    ('IMP', 'Imprimante'),
    ('KAR', 'Karcher'),
    ('LIG', 'Ligne'),
    ('MEL', 'Mélangeur'),
    ('MTR', 'Metrologie'),
    ('MM', 'Monte matiére'),
    ('PER', 'Perceuse'),
    ('PCH', 'Pied de chauffe'),
    ('PLI', 'Plieuse'),
    ('POI', 'Poinconeuse'),
    ('POE', 'Pompe à eau'),
    ('POV', 'Pompe à vide'),
    ('PCB', 'Ponceuse  bande'),
    ('PRL', 'Pont roulant'),
    ('POU', 'Poubelle'),
    ('PRE', 'Presse'),
    ('PIJ', 'Presse à injecter'),
    ('PRM', 'Presse manuel'),
    ('RBT', 'Raboteuse'),
    ('REC', 'Réchauffeur'),
    ('RCT', 'Réctifieuse'),
    ('SBL', 'Sableuse'),
    ('SCI', 'Scie '),
    ('SCH', 'Sécheur'),
    ('STU', 'Structureuse'),
    ('SBB', 'Support BIG BAG'),
    ('TAB', 'Table'),
    ('TDP', 'Tapis de poncage '),
    ('TRD', 'Taraudeuse'),
    ('TEN', 'Tenoneuse'),
    ('TOU', 'Toupie'),
    ('TOR', 'Tour'),
    ('TRM', 'Touret à meulé'),
    ('TRA', 'Transpalette'),
    ('TPE', 'Transpalette électrique'),
    ('OTH', 'Travail en hauteur'),
    ('TRY', 'Trémie '),
    ('VIL', 'Viellisement'),
    ('VHL', 'VL')
ON CONFLICT (code) DO UPDATE SET label = EXCLUDED.label;